a = input ('Digite Algo: ')
print ('Variavel é =',type(a))
print ('Tem Espaço =', a.isspace())
print ('É Numero =', a.isnumeric())
print ('É Alfabetico =', a.isalpha())
print ('É Alfanumerico =', a.isalnum())
print ('Maiuscula" =', a.isupper())
print ('Minuscula" =', a.islower())
